export const lineages = [
  { root: "ABAP", descendants: ["SAP 4GL", "Advanced ABAP", "RAP (RESTful ABAP Programming Model)"] },
  { root: "ActionScript", descendants: ["Flash", "Flex", "Haxe", "TypeScript"] },
  { root: "Ada", descendants: ["SPARK", "VHDL", "Eiffel", "GNAT", "Ravenscar"] },
  { root: "Agda", descendants: ["Idris", "Lean", "Coq", "F*"] },
  { root: "ALGOL", descendants: ["Pascal", "Modula-2", "Ada", "C", "Algol68", "Simula"] },
  { root: "Alice", descendants: ["Squeak", "Scratch", "Snap!", "Greenfoot"] },
  { root: "APL", descendants: ["J", "K", "Q", "BQN", "Nial"] },
  { root: "Apex", descendants: ["Lightning Flow", "Salesforce DX", "LWC (Lightning Web Components)"] },
  { root: "Arduino C", descendants: ["Wiring", "Arduino IDE", "PlatformIO", "ESP-IDF"] },
  { root: "ASP.NET", descendants: ["Razor", "Blazor", "MAUI", ".NET Core WebAPI"] },
  { root: "ATS", descendants: ["Cyclone", "Rust", "ATS2", "F*", "Vale", "Dafny"] },
  { root: "AutoHotkey", descendants: ["AutoIt", "Pulover’s Macro Creator", "AHK v2"] },
  { root: "AutoIt", descendants: ["AutoHotkey", "Sikuli", "WinAutomation", "Power Automate"] },
  { root: "AWK", descendants: ["Perl", "Python", "sed", "jq", "mawk"] },
  { root: "Axiom", descendants: ["FriCAS", "OpenAxiom", "SageMath"] },
  { root: "B", descendants: ["C", "BCPL", "C++", "Objective-C", "Go", "Zig"] },
  { root: "Bash", descendants: ["Zsh", "Fish", "Nushell", "Oil Shell"] },
  { root: "Batch", descendants: ["PowerShell", "CMD.EXE", "Windows Script Host", "WMI Scripting"] },
  { root: "bc", descendants: ["dc", "calc", "Python", "NumPy"] },
  { root: "BibTeX", descendants: ["BibLaTeX", "CSL JSON", "Zotero", "Mendeley"] },
  { root: "Boo", descendants: ["IronPython", "Nemerle", "F#", "Kotlin", "Scala"] },
  { root: "Brainfuck", descendants: ["Befunge", "Piet", "Malbolge", "Ook!", "JSFuck"] },
  { root: "C", descendants: ["C++", "Objective-C", "C#", "D", "Rust", "Zig", "Go", "V", "Nim"] },
  { root: "C#", descendants: ["F#", "VB.NET", "TypeScript", "Kotlin", "Swift", "Carbon", "Dart"] },
  { root: "C++", descendants: ["Objective-C++", "D", "Rust", "Carbon", "Zig", "Jai"] },
  { root: "Cairo", descendants: ["Noir", "Leo", "Lurk", "zkLLVM", "SnarkyJS"] },
  { root: "Chapel", descendants: ["X10", "UPC", "Julia (for HPC)", "Legion"] },
  { root: "Clarity", descendants: ["Move", "Pact", "Solidity", "Scilla"] },
  { root: "Clojure", descendants: ["Babashka", "ClojureScript", "Hy", "Fennel", "Janet"] },
  { root: "COBOL", descendants: ["PL/I", "RPG", "Visual COBOL", "Micro Focus COBOL"] },
  { root: "CoffeeScript", descendants: ["TypeScript", "JSX", "ES6", "ReScript"] },
  { root: "CSS", descendants: ["Sass", "SCSS", "Less", "Stylus", "Tailwind", "PostCSS", "Emotion"] },
  { root: "CUDA", descendants: ["OpenCL", "HIP", "SYCL", "Triton", "Mojo"] },
  { root: "D", descendants: ["Rust", "Zig", "V", "Odin", "Jai"] },
  { root: "Datalog", descendants: ["Soufflé", "LogicBlox", "Datomic", "Flix"] },
  { root: "Delphi", descendants: ["Lazarus", "Free Pascal", "Oxygene", "Smart Pascal"] },
  { root: "Dhall", descendants: ["Cue", "Jsonnet", "Nickel", "Starlark", "Rego"] },
  { root: "Dockerfile", descendants: ["Compose", "BuildKit", "Podman", "Nix", "Bazel"] },
  { root: "Dragon", descendants: ["Drake", "PyDragon", "OpenAI Gym DSL", "ReinforceScript"] },
  { root: "EBNF", descendants: ["BNF", "PEG", "ANTLR", "Tree-sitter"] },
  { root: "Eiffel", descendants: ["SPARK", "Ada", "D", "Design by Contract", "Sather"] },
  { root: "Elixir", descendants: ["Erlang", "Gleam", "LFE", "Nitrogen", "Phoenix"] },
  { root: "Elm", descendants: ["PureScript", "ReScript", "ReasonML", "TypeScript JSX"] },
  { root: "Erlang", descendants: ["Elixir", "Gleam", "Pony", "Akka", "Cloud Haskell"] },
  { root: "Euphoria", descendants: ["Phix", "RapidQ", "Liberty BASIC"] },
  { root: "F#", descendants: ["OCaml", "Scala", "Haskell", "Kotlin", "Elm", "ReScript"] },
  { root: "Factor", descendants: ["Joy", "Cat", "PostScript", "Forth", "Concatenative families"] },
  { root: "Falcon", descendants: ["Python", "Lua", "Wren", "Nim", "Zig"] },
  { root: "Fennel", descendants: ["Lua", "Clojure", "Janet", "Wisp"] },
  { root: "Forth", descendants: ["Factor", "PostScript", "RPL", "Joy", "ColorForth", "RetroForth"] },
  { root: "Fortran", descendants: ["ALGOL", "MATLAB", "Julia", "NumPy", "Fortran 2008"] },
  { root: "FoxPro", descendants: ["dBase", "xBase", "Clipper", "Harbour"] },
  { root: "Frege", descendants: ["Haskell", "Eta", "Kotlin", "Arrow"] },
  { root: "Genie", descendants: ["Vala", "GNOME Shell Extensions", "GTK4", "Rust GTK"] },
  { root: "Gherkin", descendants: ["Cucumber", "Behave", "Lettuce", "Robot Framework"] },
  { root: "GLSL", descendants: ["HLSL", "Metal", "SPIR-V", "WGSL", "ShaderLab", "Slang"] },
  { root: "Go", descendants: ["Rust", "Zig", "V", "Odin", "TinyGo", "Wren"] },
  { root: "Gosu", descendants: ["Guidewire Studio", "Kotlin", "JavaFX", "Groovy"] },
  { root: "GraphQL SDL", descendants: ["Apollo", "Nexus", "Prisma", "Hasura", "PostGraphile"] },
  { root: "Groovy", descendants: ["Gradle DSL", "Kotlin Script", "Spock", "Griffon", "Micronaut"] },
  { root: "GSQL", descendants: ["Cypher", "Gremlin", "SPARQL", "ArangoQL"] },
  { root: "Haskell", descendants: ["PureScript", "Elm", "F#", "OCaml", "Idris", "Agda", "Lean"] },
  { root: "Haxe", descendants: ["OpenFL", "Lime", "Kha", "Heaps", "Stencyl"] },
  { root: "HTML", descendants: ["XML", "XHTML", "JSX", "QML", "Astro", "Svelte"] },
  { root: "Hy", descendants: ["Clojure", "MacroPy", "Coconut", "Fennel"] },
  { root: "Hoon", descendants: ["Urbit", "Arvo", "Nock", "Ford", "Eyre"] },
  { root: "Io", descendants: ["Smalltalk", "Self", "Lua", "Wren", "Janet"] },
  { root: "Isabelle", descendants: ["Coq", "Agda", "Lean", "HOL Light", "PVS"] },
  { root: "Idris", descendants: ["Agda", "F*", "Coq", "Lean", "ATS", "Luna"] },
  { root: "Icon", descendants: ["Unicon", "SNOBOL", "Rexx", "TMG"] },
  { root: "J", descendants: ["K", "Q", "BQN", "APL", "NumPy", "JAX"] },
  { root: "Java", descendants: ["Kotlin", "Scala", "Groovy", "Clojure", "Gosu", "Xtend", "XtLang"] },
  { root: "JavaScript", descendants: ["TypeScript", "JSX", "ReScript", "Elm", "Svelte", "Astro"] },
  { root: "Jinja2", descendants: ["Django Templates", "Liquid", "Handlebars", "Mustache", "EJS", "Nunjucks"] },
  { root: "JCL", descendants: ["REXX", "CLIST", "IBM JCL", "z/OS Shell", "Jython"] },
  { root: "JSON", descendants: ["YAML", "TOML", "Dhall", "Cue", "JSON5"] },
  { root: "Julia", descendants: ["Mojo", "Rust", "Fortran", "MATLAB", "CUDA"] },
  { root: "K", descendants: ["Q", "BQN", "J", "Kdb+", "APL", "Nial"] },
  { root: "Kotlin", descendants: ["Scala", "Java", "Groovy", "Swift", "Dart", "F#"] },
  { root: "KRL", descendants: ["CEP DSL", "RuleML", "Drools", "CLIPS"] },
  { root: "LabVIEW G", descendants: ["Simulink", "Node-RED", "Blockly", "Scratch", "MAXScript"] },
  { root: "LaTeX", descendants: ["Markdown", "Typst", "AsciiDoc", "Pandoc", "Org-mode", "Quarto"] },
  { root: "Lean", descendants: ["Coq", "Agda", "Idris", "F*", "TheoremScript"] },
  { root: "Lex", descendants: ["Flex", "Ragel", "RE2C", "ANTLR", "PEG"] },
  { root: "Lisp", descendants: ["Scheme", "Common Lisp", "Emacs Lisp", "Clojure", "Racket", "Hy", "Janet"] },
  { root: "LLVM IR", descendants: ["MLIR", "SPIR-V", "WebAssembly", "CIRCT", "Cranelift"] },
  { root: "Logtalk", descendants: ["Prolog", "Mercury", "Flora-2", "Tau Prolog", "Datalog"] },
  { root: "Lua", descendants: ["Fennel", "Moonscript", "Wren", "Teal", "LÖVE Engine", "Pico-8 Script"] },
  { root: "Makefile", descendants: ["CMake", "Meson", "Ninja", "Bazel", "Pants", "Buck"] },
  { root: "Maple", descendants: ["Mathematica", "SymPy", "SageMath", "Maxima", "GiNaC"] },
  { root: "Markdown", descendants: ["reStructuredText", "AsciiDoc", "Org-mode", "Typst", "Quarto", "MDX"] },
  { root: "Mathematica / Wolfram", descendants: ["SageMath", "Maple", "SymPy", "Julia", "Mathematica Online"] },
  { root: "MATLAB", descendants: ["Octave", "Scilab", "Julia", "NumPy", "JAX"] },
  { root: "Meson", descendants: ["CMake", "Ninja", "Bazel", "Tup"] },
  { root: "Modula-2", descendants: ["Oberon", "Ada", "Component Pascal", "Modula-3", "Delphi"] },
  { root: "Mojo", descendants: ["Python", "Julia", "Rust", "Swift", "Triton", "AI DSLs"] },
  { root: "Move", descendants: ["Clarity", "Pact", "Solidity", "Rust Smart Contracts"] },
  { root: "MythScript", descendants: ["Hollow Light Script", "DreamWeaver DSL", "EtherCode"] },
  { root: "NASL", descendants: ["Nessus", "OpenVAS", "Metasploit", "Nmap NSE"] },
  { root: "Nemerle", descendants: ["F#", "Kotlin", "Scala", "Boo", "Nix"] },
  { root: "Nim", descendants: ["V", "Zig", "Odin", "Crystal", "Red", "Jai"] },
  { root: "Nix", descendants: ["Guix", "Bazel", "Dockerfile", "Cue", "Dhall"] },
  { root: "NSIS", descendants: ["Inno Setup", "WiX", "InstallShield", "AppImage", "Flatpak"] },
  { root: "NumPy", descendants: ["SciPy", "TensorFlow", "PyTorch", "JAX", "CuPy"] },
  { root: "Objective-C", descendants: ["Swift", "Objective-C++", "Carbon", "Kotlin/Native"] },
  { root: "OCaml", descendants: ["ReasonML", "ReScript", "F#", "Elm", "Unison"] },
  { root: "OpenCL", descendants: ["CUDA", "Metal", "SYCL", "ROCm", "Triton", "Mojo"] },
  { root: "OpenQASM", descendants: ["Q#", "Cirq", "Qiskit", "PennyLane", "PyQuil"] },
  { root: "Oz", descendants: ["Alice", "Mozart", "E", "Unison", "Erlang"] },
  { root: "Odin", descendants: ["Jai", "Zig", "V", "Carbon"] },
  { root: "Pact", descendants: ["Move", "Clarity", "Scilla", "Solidity", "Ink!"] },
  { root: "Pascal", descendants: ["Modula-2", "Delphi", "Object Pascal", "Free Pascal", "Lazarus"] },
  { root: "Pawn", descendants: ["AMX", "Small", "SourcePawn", "SQF", "UnrealScript"] },
  { root: "Perl", descendants: ["Raku", "Python", "Ruby", "PHP", "AWK"] },
  { root: "PHP", descendants: ["Hack", "HHVM", "Twig", "Laravel Blade", "TypeScript JSX"] },
  { root: "Pig Latin", descendants: ["HiveQL", "SparkSQL", "Flink", "Trino", "DuckDB SQL"] },
  { root: "PicoLisp", descendants: ["NewLisp", "uLisp", "Janet", "Hy"] },
  { root: "PL/SQL", descendants: ["T-SQL", "PostgreSQL PL/pgSQL", "PLV8", "DuckDB SQL"] },
  { root: "PostScript", descendants: ["PDF", "SVG", "EPS", "Ghostscript", "PDFium"] },
  { root: "PowerShell", descendants: ["Pwsh Core", ".NET CLI", "Azure CLI", "DSC", "YAML Pipelines"] },
  { root: "Prolog", descendants: ["Mercury", "Logtalk", "Tau Prolog", "Flora-2", "SWI-Prolog"] },
  { root: "Promela", descendants: ["TLA+", "Alloy", "PlusCal", "Spin", "Ivy"] },
  { root: "Python", descendants: ["Ruby", "Julia", "Mojo", "Coconut", "PyPy", "MicroPython", "RustPython"] },
  { root: "Q", descendants: ["K", "Q#", "Qiskit", "Cirq", "QuantumFlow"] },
  { root: "Q#", descendants: ["OpenQASM", "Cirq", "PyQuil", "Qiskit", "Braket"] },
  { root: "QML", descendants: ["Qt Quick", "QML2", "Kirigami", "Godot GDScript", "Flutter Dart"] },
  { root: "R", descendants: ["RMarkdown", "Tidyverse", "ggplot", "Julia", "DuckDB SQL"] },
  { root: "Racket", descendants: ["Typed Racket", "Pyret", "Rhombus", "Gerbil", "Hop"] },
  { root: "Ragel", descendants: ["RE2C", "Flex", "ANTLR", "Tree-sitter"] },
  { root: "ReasonML", descendants: ["ReScript", "BuckleScript", "OCaml", "JSX", "TypeScript"] },
  { root: "ReScript", descendants: ["JSX", "React", "TypeScript", "Elm"] },
  { root: "Rexx", descendants: ["NetRexx", "ooRexx", "Regina", "IBM REXX", "z/OS REXX"] },
  { root: "Ring", descendants: ["Wren", "Nim", "Odin", "DragonLang"] },
  { root: "Robot Framework", descendants: ["Gherkin", "Behave", "Lettuce", "Cucumber"] },
  { root: "Ruby", descendants: ["Crystal", "Elixir", "Python", "Rails DSLs", "Sorbet"] },
  { root: "Rust", descendants: ["Zig", "V", "Odin", "Carbon", "Mojo", "Vale"] },
  { root: "Sass / SCSS", descendants: ["Less", "Stylus", "PostCSS", "Tailwind", "Emotion"] },
  { root: "Scala", descendants: ["Kotlin", "Clojure", "F#", "Swift", "Dotty (Scala 3)"] },
  { root: "Scheme", descendants: ["Common Lisp", "Racket", "Clojure", "Guile", "Hy", "Janet"] },
  { root: "Sed", descendants: ["AWK", "Perl", "grep", "jq", "ripgrep"] },
  { root: "Self", descendants: ["Io", "JavaScript", "Lua", "Smalltalk", "Wren"] },
  { root: "ShaderLab", descendants: ["HLSL", "GLSL", "WGSL", "Slang", "Godot Shader", "Unity Shader Graph"] },
  { root: "Shell (POSIX)", descendants: ["Bash", "Zsh", "Fish", "Nushell", "Oil Shell", "Xonsh"] },
  { root: "Smalltalk", descendants: ["Self", "Squeak", "Pharo", "Newspeak", "Io", "Etoys"] },
  { root: "SNOBOL", descendants: ["Icon", "Unicon", "Rexx", "AWK"] },
  { root: "SPARK (Ada)", descendants: ["Ada", "SPARK 2014", "GNATprove", "VHDL", "Eiffel"] },
  { root: "SPSS Syntax", descendants: ["R", "Python", "SAS", "Stata", "PSPP"] },
  { root: "SQL", descendants: ["PL/SQL", "T-SQL", "MySQL", "PostgreSQL", "SQLite", "DuckDB"] },
  { root: "Squirrel", descendants: ["Lua", "Pawn", "AngelScript", "Wren"] },
  { root: "Stylus", descendants: ["Sass", "Less", "PostCSS", "Tailwind"] },
  { root: "SuperCollider", descendants: ["ChucK", "TidalCycles", "FoxDot", "Sonic Pi"] },
  { root: "Swift", descendants: ["Kotlin", "Dart", "Carbon", "Mojo", "Zig", "SwiftUI DSL"] },
  { root: "Tcl", descendants: ["Tk", "Expect", "Itcl", "Jim Tcl", "XOTcl"] },
  { root: "TeX", descendants: ["LaTeX", "BibTeX", "XeTeX", "LuaTeX", "ConTeXt"] },
  { root: "TLA+", descendants: ["PlusCal", "Alloy", "Promela", "Ivy", "Coq"] },
  { root: "TOML", descendants: ["JSON", "YAML", "Dhall", "Cue", "Nickel"] },
  { root: "TypeScript", descendants: ["ReScript", "Flow", "JSX", "ReasonML", "Elm"] },
  { root: "Turing", descendants: ["Ada", "Modula-2", "C", "Pascal", "Python"] },
  { root: "Unison", descendants: ["Elm", "Haskell", "OCaml", "Pony", "Purescript"] },
  { root: "UnrealScript", descendants: ["Blueprints", "Verse", "UMG", "C++ UE DSL"] },
  { root: "Ur", descendants: ["Ur/Web", "Elm", "Haskell", "ReasonML"] },
  { root: "V", descendants: ["Zig", "Odin", "Rust", "Jai", "Carbon", "V2Lang"] },
  { root: "V#", descendants: ["C#", "Swift", "Kotlin", "Dart", "F#"] },
  { root: "VBA", descendants: ["VB.NET", "PowerShell", "ExcelScript", "Office.js"] },
  { root: "VHDL", descendants: ["Verilog", "SystemVerilog", "Chisel", "SpinalHDL"] },
  { root: "Vimscript", descendants: ["Lua", "Neovim Lua", "Treesitter Configs", "Helix Config DSL"] },
  { root: "Visual Basic", descendants: ["VB.NET", "C#", "F#", "PowerShell", "WinUI DSL"] },
  { root: "Visual FoxPro", descendants: ["dBase", "Clipper", "Harbour", "SQL Server Express"] },
  { root: "Vue Template Syntax", descendants: ["JSX", "Astro", "Svelte", "Solid.js", "Qwik"] },
  { root: "WebAssembly Text (WAT)", descendants: ["AssemblyScript", "Rust", "TinyGo", "C", "Zig", "C++"] },
  { root: "Wren", descendants: ["Odin", "V", "Crystal", "Grain", "Rune"] },
  { root: "Wolfram", descendants: ["Julia", "SymPy", "SageMath", "Maple", "Maxima"] },
  { root: "X10", descendants: ["Chapel", "UPC++", "Legion", "Charm++", "HPX"] },
  { root: "X++", descendants: ["C#", "F#", "XAL", "Power Fx", "Dataverse DSL"] },
  { root: "XAML", descendants: ["WPF", "UWP", "MAUI", "WinUI", "Avalonia"] },
  { root: "XML", descendants: ["JSON", "YAML", "TOML", "Dhall", "Cue"] },
  { root: "XQuery", descendants: ["XPath", "XSLT", "GraphQL", "Cypher", "SQL"] },
  { root: "XSLT", descendants: ["XML", "XQuery", "XPath", "JSONata"] },
  { root: "YAML", descendants: ["JSON", "TOML", "Dhall", "Cue", "Nickel"] },
  { root: "YANG", descendants: ["NETCONF", "RESTCONF", "gNMI", "OpenConfig", "CloudFormation"] },
  { root: "Yorick", descendants: ["IDL", "MATLAB", "Python", "Julia", "NumPy"] },
  { root: "Zeek", descendants: ["Bro", "Suricata", "Wireshark Lua", "Snort"] },
  { root: "Zeno", descendants: ["TLA+", "Promela", "Alloy", "B Method", "VDM-SL"] },
  { root: "Zig", descendants: ["Odin", "V", "Rust", "Jai", "Carbon", "Mojo"] },
  { root: "ZIL", descendants: ["Inform", "TADS", "Twine", "Ink", "Ren’Py"] },
  { root: "Zookeeper DSL", descendants: ["YAML", "JSON", "KDL", "CUE", "Rego"] },
  { root: "Zsh", descendants: ["Bash", "Fish", "Nushell", "Oil Shell", "Xonsh"] },
  { root: "ZedScript", descendants: ["VS Code API", "LSP", "Neovim Lua", "Rome", "Biome", "Zed Ext DSL"] }
];
